import { useState } from "react";
import "./App.css";

function App() {
    const [code, setCode] = useState(`const users = [1, 2, 3, 4, 5];

for (let i = 0; i < users.length; i++) {
    for (let j = 0; j < users.length; j++) {
        console.log(users[i]);
    }
}`);

    const [points, setPoints] = useState(0);
    const [analyzed, setAnalyzed] = useState(false);
    const [accepted, setAccepted] = useState(false);
    const [scanning, setScanning] = useState(false);
    const [result, setResult] = useState(null);

    // ============================================
    // ANALYZE CODE
    // ============================================

    const analyzeCode = async () => {
        if (!code.trim()) {
            alert("Please enter some JavaScript code first.");
            return;
        }

        setScanning(true);
        setAnalyzed(false);
        setAccepted(false);
        setResult(null);

        console.log("📤 Sending code to SyntaxX backend...");
        console.log(code);

        try {
            const response = await fetch(
                "http://localhost:5000/analyze",
                {
                    method: "POST",

                    headers: {
                        "Content-Type": "application/json",
                    },

                    body: JSON.stringify({
                        code: code,
                    }),
                }
            );

            const data = await response.json();

            console.log("📥 Backend response:");
            console.log(data);

            if (!response.ok) {
                throw new Error(
                    data.error || "Analysis failed"
                );
            }

            const inefficient =
                data.analysis &&
                data.analysis.nestedLoops > 0;

            setResult({
                inefficient: inefficient,

                title: inefficient
                    ? "Nested Loop Detected"
                    : "Code Looks Efficient",

                explanation:
                    data.analysis.message,

                alternative:
                    data.aiResult,

                benefit: data.aiResult
                    ? "🤖 This recommendation was generated by SyntaxX AI using Gemini."
                    : "SyntaxX did not detect a major inefficiency in your code.",
            });

            setAnalyzed(true);

        } catch (error) {
            console.error(
                "❌ SyntaxX Error:",
                error
            );

            alert(
                "SyntaxX Error: " +
                error.message
            );

        } finally {
            setScanning(false);
        }
    };

    // ============================================
    // ACCEPT OPTIMIZATION
    // ============================================

    const acceptAlternative = () => {
        setPoints(
            (previous) => previous + 50
        );

        setAccepted(true);
    };

    // ============================================
    // EARTH LEVEL
    // ============================================

    const level =
        Math.floor(points / 50) + 1;

    return (
        <div className="app">

            {/* ================= HEADER ================= */}

            <header>

                <div className="logo">
                    🌱 SyntaxX
                </div>

                <div className="points">
                    🌱 {points} Eco Points
                </div>

            </header>


            <main>

                {/* ================= HERO ================= */}

                <section className="hero">

                    <div className="badge">
                        ♻️ GREEN CODING ASSISTANT
                    </div>

                    <h1>
                        Code for a{" "}
                        <span>
                            Greener Planet
                        </span>{" "}
                        🌍
                    </h1>

                    <p>
                        Write code. Detect inefficiencies.
                        Discover greener alternatives.
                        Grow your virtual Earth.
                    </p>

                </section>


                {/* ================= GAME ================= */}

                <div className="game">


                    {/* ================= CODE EDITOR ================= */}

                    <div className="code-card">

                        <div className="card-title">

                            <h2>
                                💻 Your Code
                            </h2>

                            <span className="javascript">
                                JavaScript
                            </span>

                        </div>


                        <textarea
                            value={code}

                            onChange={(event) => {
                                setCode(
                                    event.target.value
                                );

                                setAnalyzed(false);
                                setAccepted(false);

                                // Remove old result
                                setResult(null);
                            }}

                            spellCheck="false"

                            placeholder="Paste your JavaScript code here..."
                        />


                        <button
                            onClick={analyzeCode}
                            disabled={scanning}
                        >

                            {scanning
                                ? "🔄 Analyzing..."
                                : "🔍 Analyze Code"}

                        </button>

                    </div>


                    {/* ================= EARTH ================= */}

                    <div className="earth-card">

                        <div className="earth">

                            {level >= 3
                                ? "🌎"
                                : "🌍"}

                        </div>


                        <h2>
                            My Eco World
                        </h2>


                        <div className="level">
                            Earth Level {level}
                        </div>


                        <div className="trees">

                            {"🌳".repeat(
                                Math.min(
                                    level,
                                    8
                                )
                            )}

                        </div>


                        <div className="progress">

                            <div
                                className="progress-bar"

                                style={{
                                    width: `${Math.min(
                                        level * 25,
                                        100
                                    )}%`,
                                }}
                            />

                        </div>


                        <p>

                            {points === 0
                                ? "Optimize your code to start healing your planet."
                                : "Every optimization makes your planet healthier."}

                        </p>

                    </div>

                </div>


                {/* ================= ANALYSIS RESULT ================= */}

                {analyzed && result && (

                    <div
                        className={
                            result.inefficient
                                ? "alert"
                                : "alert efficient"
                        }
                    >

                        <div className="warning-icon">

                            {result.inefficient
                                ? "⚠️"
                                : "✅"}

                        </div>


                        <div className="analysis-content">


                            {/* RESULT TITLE */}

                            <h2>
                                {result.title}
                            </h2>


                            {/* ANALYZER MESSAGE */}

                            <p className="problem">
                                {result.explanation}
                            </p>


                            {/* ================= AI RECOMMENDATION ================= */}

                            {result.inefficient &&
                                result.alternative && (

                                    <div className="ai-box">

                                        <h3>
                                            🤖 SyntaxX AI Recommendation
                                        </h3>

                                        <p>
                                            {result.benefit}
                                        </p>

                                        <pre className="alternative">
                                            {result.alternative}
                                        </pre>

                                    </div>

                                )}


                            {/* ================= ACCEPT BUTTON ================= */}

                            {result.inefficient &&
                                !accepted && (

                                    <button
                                        className="accept"

                                        onClick={
                                            acceptAlternative
                                        }
                                    >

                                        ✅ Accept Alternative
                                        {" "}+50 Eco Points

                                    </button>

                                )}


                            {/* ================= SUCCESS ================= */}

                            {accepted && (

                                <div className="success">

                                    🎉 Optimization accepted!

                                    <br />

                                    <span>
                                        🌱 +50 Eco Points • Your Earth is healthier!
                                    </span>

                                </div>

                            )}

                        </div>

                    </div>

                )}


                {/* ================= INSTRUCTION ================= */}

                {!analyzed &&
                    !scanning && (

                        <div className="instruction">

                            💡 Paste your JavaScript code
                            above and click{" "}

                            <b>
                                Analyze Code
                            </b>
                            .

                        </div>

                    )}

            </main>

        </div>
    );
}

export default App;